sudo: required
services:
  - docker

before_install: 
  - docker build -t satya18/react-test -f ./client/Dockerfile.dev

script: 
  - docker run -e CI=true USERNAME/react-test npm test

after_success: 
  - docker build -t satya18/multi-client ./client
  - docker build -t satya18/multi-nginx ./nginx
  - docker build -t satya18/multi-server ./server
  - docker build -t satya18/multi-worker ./worker
